import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#703700",
        "on-secondary-container": "#00302b",
        "primary-container": "#8083ff",
        "primary-fixed-dim": "#c0c1ff",
        "on-tertiary": "#4f2500",
        "inverse-surface": "#dae2fd",
        "outline-variant": "#464554",
        secondary: "#6bd8cb",
        "on-error": "#690005",
        "surface-container-low": "#131b2e",
        "surface-dim": "#0b1326",
        "tertiary-container": "#d97721",
        "on-surface-variant": "#c7c4d7",
        "on-primary-container": "#0d0096",
        "on-tertiary-fixed": "#301400",
        "surface-tint": "#c0c1ff",
        "secondary-fixed": "#89f5e7",
        error: "#ffb4ab",
        "on-secondary": "#003732",
        "on-secondary-fixed-variant": "#005049",
        tertiary: "#ffb783",
        "surface-bright": "#31394d",
        "on-background": "#dae2fd",
        "on-primary": "#1000a9",
        "primary-fixed": "#e1e0ff",
        "on-secondary-fixed": "#00201d",
        "inverse-on-surface": "#283044",
        "secondary-container": "#29a195",
        "secondary-fixed-dim": "#6bd8cb",
        outline: "#908fa0",
        "on-error-container": "#ffdad6",
        "surface-container-high": "#222a3d",
        "surface-container-lowest": "#060e20",
        background: "#0b1326",
        "on-primary-fixed-variant": "#2f2ebe",
        "error-container": "#93000a",
        "tertiary-fixed-dim": "#ffb783",
        surface: "#0b1326",
        "on-primary-fixed": "#07006c",
        "surface-container-highest": "#2d3449",
        "on-tertiary-container": "#452000",
        "on-surface": "#dae2fd",
        "surface-variant": "#2d3449",
        "tertiary-fixed": "#ffdcc5",
        primary: "#c0c1ff",
        "inverse-primary": "#494bd6",
        "surface-container": "#171f33",
      },
      fontFamily: {
        headline: ["var(--font-headline)", "sans-serif"],
        body: ["var(--font-body)", "sans-serif"],
        label: ["var(--font-body)", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};

export default config;

